const Routes = {
  HOME_SCREEN: 'Home',
  LOADING: 'LOADING',

  LOGIN_STACK: 'LOGIN_STACK',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  MAIN_APP: 'MAIN_APP', //DRAWER

  APP_INTRO: 'APP_INTRO',

  HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
  HOME_TABS: 'HOME_TABS', //HOME TABS

  PROFILE_SCREEN: 'Profile',
  SEARCH_SCREEN: 'Explore',
  PEOPLE_SCREEN: 'People',
  SETTINGS_SCREEN: 'Settings',
};

export default Routes;
